### POST Create new patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "firstName": "Lahiruka 123",
  "lastName": "Kamal 122",
  "email": "dishLAHI@gmail12345.com",
  "dateOfBirth": "1992-05-05T00:00:00",
  "dateOfRegistration": "2015-03-15T23:06:21.101357"
}

###