### POST Create new patient
POST http://localhost:4000/patients
Content-Type: application/json

{
  "firstName": "Lahiruka",
  "lastName": "Kamal",
  "email": "dishLAHI@gmail.co",
  "dateOfBirth": "1992-05-05T00:00:00",
  "dateOfRegistration": "2015-03-15T23:06:21.101357"
}

###